### ISSUE TITLE
The map does not match the seed IG (Terralith, Tectonic, Continents)

### ISSUE THREAD

**Issue by Shunkaha** [jacobsjo/mc-datapack-map#38] opened 2024-03-31 18:15 UTC
The map displayed using the Continents, Terralith and Tectonic mods does not correspond to the in-game seed.
However, the spawn point is within a few blocks of the correct location and biome.

I tried using only Terralith and Tectonic. In this case, the map is right with the in-game seed. This is also the case if I put only Continents.

But it's not the case if I try with Continents and one of the other two mods, and even more so if I try with all 3 mods.

Do you have any idea why? And how to solve this problem?

Best regards,

Shunkaha

**Comment by jacobsjo** [comment] 2024-03-31 20:19
I cannot reproduce this issue. The seeds do match in my tries. Can you please give more details on which versions of minecraft and the mods you are using? And which modloader are you using? 

Note that the map treats the mods as datapack, so the special code in tectonic to load different data when terralith is present doesn't work. To have the comparability work in the map, you need [the terratonic datapack](https://modrinth.com/datapack/terratonic/version/3.1.1) instead of tectonic. But this doesn't explain the issue you are reporting, since it apparently also happens when you just have terralith and continents?! (In which case loading the mod jar files in the map should work.)

**Comment by Shunkaha** [comment] 2024-04-01 06:02
I use Fabric as a modloader.
My game version is 1.20.4.
The mod versions are as follows:
Continents 1.20.4_v.1.1.4
Tectonic 1.20.4_v.2.2.1
Terralith 1.20.4_v.2.4.11

I have uninstalled and reinstalled Terralith and Continents following your reply. The seed now corresponds to the map. I don't understand why this wasn't the case yesterday.

Using the Terratonic Datapack, it seems to me that the seeds are identical to the map.

**Comment by jacobsjo** [comment] 2024-04-01 09:47
Good to hear its now working for you. So I'll close this issue for now. If you run into this issue again and can reproduce it, feel free to comment here and I'll reopen it again.

**Closed by jacobsjo** 2024-04-01 09:47 UTC
