### ISSUE TITLE
Ocean Monument is missing from list

### ISSUE THREAD

**Issue by robosoup2** [jacobsjo/mc-datapack-map#25] opened 2023-11-01 03:15 UTC
would love to search for ocean monuments/ check how they compare with mods or datapacks loaded!

**Comment by jacobsjo** [comment] 2023-11-01 13:29
Duplicate of #10 

I'm sorry, but ocean monuments are unfortunately one of the vanilla structures that have rather complicated placement code. Given this map is mostly about datapack maps, and most custom structures use jigsaw, ocean monuments are unfortunately too much effort to implement.

**Closed by jacobsjo** 2023-11-01 13:29 UTC

**Comment by robosoup2** [comment] 2023-11-01 15:26
no worries! I thought that might be the case haha
